"""stage2 qa schema"""

revision = 'e3fe7afe0b4a'
down_revision = '20260303_000001'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qa_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.Enum('web', 'telegram', name='session_channel_enum'), nullable=False),
    sa.Column('external_user_id', sa.String(length=255), nullable=True),
    sa.Column('external_chat_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('active', 'expired', 'closed', name='session_status_enum'), server_default='active', nullable=False),
    sa.Column('session_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_qa_sessions'))
    )
    op.create_index('ix_qa_sessions_channel_external_chat_id', 'qa_sessions', ['channel', 'external_chat_id'], unique=False)
    op.create_index('ix_qa_sessions_channel_external_user_id', 'qa_sessions', ['channel', 'external_user_id'], unique=False)
    op.create_index('ix_qa_sessions_created_at', 'qa_sessions', ['created_at'], unique=False)
    op.create_index('ix_qa_sessions_expires_at', 'qa_sessions', ['expires_at'], unique=False)
    op.create_index('ix_qa_sessions_status', 'qa_sessions', ['status'], unique=False)
    op.create_table('trusted_source_sync_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_domain', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'completed', 'failed', name='trusted_source_sync_status_enum'), server_default='pending', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('documents_discovered', sa.Integer(), server_default='0', nullable=False),
    sa.Column('documents_indexed', sa.Integer(), server_default='0', nullable=False),
    sa.Column('details_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trusted_source_sync_runs'))
    )
    op.create_index('ix_trusted_source_sync_runs_created_at', 'trusted_source_sync_runs', ['created_at'], unique=False)
    op.create_index('ix_trusted_source_sync_runs_source_domain', 'trusted_source_sync_runs', ['source_domain'], unique=False)
    op.create_index('ix_trusted_source_sync_runs_status', 'trusted_source_sync_runs', ['status'], unique=False)
    op.create_table('qa_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('user', 'assistant', 'system', 'tool', name='message_role_enum'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['qa_sessions.id'], name=op.f('fk_qa_messages_session_id_qa_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_qa_messages'))
    )
    op.create_index('ix_qa_messages_created_at', 'qa_messages', ['created_at'], unique=False)
    op.create_index('ix_qa_messages_session_id', 'qa_messages', ['session_id'], unique=False)
    op.create_table('trusted_source_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('last_sync_run_id', sa.UUID(), nullable=True),
    sa.Column('source_domain', sa.String(length=255), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['last_sync_run_id'], ['trusted_source_sync_runs.id'], name=op.f('fk_trusted_source_documents_last_sync_run_id_trusted_source_sync_runs'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trusted_source_documents')),
    sa.UniqueConstraint('source_url', name='uq_trusted_source_documents_source_url')
    )
    op.create_index('ix_trusted_source_documents_content_hash', 'trusted_source_documents', ['content_hash'], unique=False)
    op.create_index('ix_trusted_source_documents_created_at', 'trusted_source_documents', ['created_at'], unique=False)
    op.create_index('ix_trusted_source_documents_source_domain', 'trusted_source_documents', ['source_domain'], unique=False)
    op.create_table('qa_queries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'analyzing', 'retrieving', 'synthesizing', 'verifying', 'completed', 'failed', 'cancelled', name='query_status_enum'), server_default='pending', nullable=False),
    sa.Column('query_type', sa.String(length=100), nullable=True),
    sa.Column('requires_freshness_check', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('used_open_web', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('used_trusted_web', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['qa_messages.id'], name=op.f('fk_qa_queries_message_id_qa_messages'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['qa_sessions.id'], name=op.f('fk_qa_queries_session_id_qa_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_qa_queries'))
    )
    op.create_index('ix_qa_queries_created_at', 'qa_queries', ['created_at'], unique=False)
    op.create_index('ix_qa_queries_finished_at', 'qa_queries', ['finished_at'], unique=False)
    op.create_index('ix_qa_queries_message_id', 'qa_queries', ['message_id'], unique=False)
    op.create_index('ix_qa_queries_session_id', 'qa_queries', ['session_id'], unique=False)
    op.create_index('ix_qa_queries_status', 'qa_queries', ['status'], unique=False)
    op.create_table('trusted_source_chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('locator', sa.Text(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('text_tsv', postgresql.TSVECTOR(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['trusted_source_documents.id'], name=op.f('fk_trusted_source_chunks_document_id_trusted_source_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trusted_source_chunks')),
    sa.UniqueConstraint('document_id', 'chunk_index', name='uq_trusted_source_chunks_document_chunk')
    )
    op.create_index('ix_trusted_source_chunks_created_at', 'trusted_source_chunks', ['created_at'], unique=False)
    op.create_index('ix_trusted_source_chunks_document_id', 'trusted_source_chunks', ['document_id'], unique=False)
    op.create_index('ix_trusted_source_chunks_text_tsv', 'trusted_source_chunks', ['text_tsv'], unique=False, postgresql_using='gin')
    op.create_table('freshness_checks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('query_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('document_version_id', sa.UUID(), nullable=True),
    sa.Column('check_status', sa.Enum('pending', 'fresh', 'stale', 'refresh_in_progress', 'refresh_failed', 'failed', name='freshness_check_status_enum'), server_default='pending', nullable=False),
    sa.Column('local_edition_label', sa.String(length=255), nullable=True),
    sa.Column('remote_edition_label', sa.String(length=255), nullable=True),
    sa.Column('refresh_job_id', sa.UUID(), nullable=True),
    sa.Column('details_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_freshness_checks_document_id_documents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_version_id'], ['document_versions.id'], name=op.f('fk_freshness_checks_document_version_id_document_versions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['query_id'], ['qa_queries.id'], name=op.f('fk_freshness_checks_query_id_qa_queries'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['refresh_job_id'], ['ingestion_jobs.id'], name=op.f('fk_freshness_checks_refresh_job_id_ingestion_jobs'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_freshness_checks'))
    )
    op.create_index('ix_freshness_checks_check_status', 'freshness_checks', ['check_status'], unique=False)
    op.create_index('ix_freshness_checks_created_at', 'freshness_checks', ['created_at'], unique=False)
    op.create_index('ix_freshness_checks_document_id', 'freshness_checks', ['document_id'], unique=False)
    op.create_index('ix_freshness_checks_document_version_id', 'freshness_checks', ['document_version_id'], unique=False)
    op.create_index('ix_freshness_checks_query_id', 'freshness_checks', ['query_id'], unique=False)
    op.create_table('qa_answers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('query_id', sa.UUID(), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=False),
    sa.Column('answer_format', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('draft', 'completed', 'failed', name='answer_status_enum'), server_default='draft', nullable=False),
    sa.Column('coverage_status', sa.Enum('complete', 'partial', 'insufficient', name='coverage_status_enum'), server_default='partial', nullable=False),
    sa.Column('has_stale_sources', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('has_external_sources', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['query_id'], ['qa_queries.id'], name=op.f('fk_qa_answers_query_id_qa_queries'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_qa_answers')),
    sa.UniqueConstraint('query_id', name='uq_qa_answers_query_id')
    )
    op.create_index('ix_qa_answers_created_at', 'qa_answers', ['created_at'], unique=False)
    op.create_index('ix_qa_answers_status', 'qa_answers', ['status'], unique=False)
    op.create_table('qa_subtasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('query_id', sa.UUID(), nullable=False),
    sa.Column('parent_subtask_id', sa.UUID(), nullable=True),
    sa.Column('subtask_type', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'completed', 'failed', 'skipped', name='subtask_status_enum'), server_default='pending', nullable=False),
    sa.Column('priority', sa.Integer(), server_default='100', nullable=False),
    sa.Column('result_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_subtask_id'], ['qa_subtasks.id'], name=op.f('fk_qa_subtasks_parent_subtask_id_qa_subtasks'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['query_id'], ['qa_queries.id'], name=op.f('fk_qa_subtasks_query_id_qa_queries'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_qa_subtasks'))
    )
    op.create_index('ix_qa_subtasks_created_at', 'qa_subtasks', ['created_at'], unique=False)
    op.create_index('ix_qa_subtasks_parent_subtask_id', 'qa_subtasks', ['parent_subtask_id'], unique=False)
    op.create_index('ix_qa_subtasks_query_id', 'qa_subtasks', ['query_id'], unique=False)
    op.create_index('ix_qa_subtasks_status', 'qa_subtasks', ['status'], unique=False)
    op.create_table('security_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('query_id', sa.UUID(), nullable=True),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.Enum('info', 'warning', 'error', 'critical', name='security_severity_enum'), server_default='info', nullable=False),
    sa.Column('source_kind', sa.String(length=100), nullable=True),
    sa.Column('details_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['query_id'], ['qa_queries.id'], name=op.f('fk_security_events_query_id_qa_queries'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['qa_sessions.id'], name=op.f('fk_security_events_session_id_qa_sessions'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_security_events'))
    )
    op.create_index('ix_security_events_created_at', 'security_events', ['created_at'], unique=False)
    op.create_index('ix_security_events_query_id', 'security_events', ['query_id'], unique=False)
    op.create_index('ix_security_events_session_id', 'security_events', ['session_id'], unique=False)
    op.create_index('ix_security_events_severity', 'security_events', ['severity'], unique=False)
    op.create_table('verification_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('query_id', sa.UUID(), nullable=False),
    sa.Column('coverage_result', sa.Enum('pass', 'warning', 'fail', name='verification_result_enum'), nullable=False),
    sa.Column('citation_result', sa.Enum('pass', 'warning', 'fail', name='verification_result_enum'), nullable=False),
    sa.Column('hallucination_result', sa.Enum('pass', 'warning', 'fail', name='verification_result_enum'), nullable=False),
    sa.Column('source_labeling_result', sa.Enum('pass', 'warning', 'fail', name='verification_result_enum'), nullable=False),
    sa.Column('warnings_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['query_id'], ['qa_queries.id'], name=op.f('fk_verification_reports_query_id_qa_queries'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_verification_reports'))
    )
    op.create_index('ix_verification_reports_created_at', 'verification_reports', ['created_at'], unique=False)
    op.create_index('ix_verification_reports_query_id', 'verification_reports', ['query_id'], unique=False)
    op.create_table('audit_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('query_id', sa.UUID(), nullable=True),
    sa.Column('subtask_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('actor_kind', sa.String(length=100), nullable=False),
    sa.Column('payload_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['query_id'], ['qa_queries.id'], name=op.f('fk_audit_events_query_id_qa_queries'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['qa_sessions.id'], name=op.f('fk_audit_events_session_id_qa_sessions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subtask_id'], ['qa_subtasks.id'], name=op.f('fk_audit_events_subtask_id_qa_subtasks'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_events'))
    )
    op.create_index('ix_audit_events_created_at', 'audit_events', ['created_at'], unique=False)
    op.create_index('ix_audit_events_event_type', 'audit_events', ['event_type'], unique=False)
    op.create_index('ix_audit_events_query_id', 'audit_events', ['query_id'], unique=False)
    op.create_index('ix_audit_events_session_id', 'audit_events', ['session_id'], unique=False)
    op.create_index('ix_audit_events_subtask_id', 'audit_events', ['subtask_id'], unique=False)
    op.create_table('qa_evidence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('query_id', sa.UUID(), nullable=False),
    sa.Column('subtask_id', sa.UUID(), nullable=True),
    sa.Column('source_kind', sa.Enum('normative', 'trusted_web', 'open_web', name='evidence_source_kind_enum'), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('document_version_id', sa.UUID(), nullable=True),
    sa.Column('node_id', sa.UUID(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('source_domain', sa.String(length=255), nullable=True),
    sa.Column('edition_label', sa.String(length=255), nullable=True),
    sa.Column('locator', sa.Text(), nullable=True),
    sa.Column('quote', sa.Text(), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('freshness_status', sa.Enum('fresh', 'stale', 'refresh_in_progress', 'refresh_failed', 'unknown', name='freshness_status_enum'), server_default='unknown', nullable=False),
    sa.Column('is_normative', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('requires_verification', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_qa_evidence_document_id_documents'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_version_id'], ['document_versions.id'], name=op.f('fk_qa_evidence_document_version_id_document_versions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['node_id'], ['document_nodes.id'], name=op.f('fk_qa_evidence_node_id_document_nodes'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['query_id'], ['qa_queries.id'], name=op.f('fk_qa_evidence_query_id_qa_queries'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subtask_id'], ['qa_subtasks.id'], name=op.f('fk_qa_evidence_subtask_id_qa_subtasks'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_qa_evidence'))
    )
    op.create_index('ix_qa_evidence_created_at', 'qa_evidence', ['created_at'], unique=False)
    op.create_index('ix_qa_evidence_document_id', 'qa_evidence', ['document_id'], unique=False)
    op.create_index('ix_qa_evidence_document_version_id', 'qa_evidence', ['document_version_id'], unique=False)
    op.create_index('ix_qa_evidence_node_id', 'qa_evidence', ['node_id'], unique=False)
    op.create_index('ix_qa_evidence_query_id', 'qa_evidence', ['query_id'], unique=False)
    op.create_index('ix_qa_evidence_source_domain', 'qa_evidence', ['source_domain'], unique=False)
    op.create_index('ix_qa_evidence_source_kind', 'qa_evidence', ['source_kind'], unique=False)
    op.create_index('ix_qa_evidence_subtask_id', 'qa_evidence', ['subtask_id'], unique=False)
    op.create_table('search_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('query_id', sa.UUID(), nullable=True),
    sa.Column('subtask_id', sa.UUID(), nullable=True),
    sa.Column('provider_name', sa.String(length=100), nullable=False),
    sa.Column('search_scope', sa.Enum('trusted_web', 'open_web', name='search_scope_enum'), nullable=False),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('allowed_domains', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('result_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('completed', 'failed', name='search_status_enum'), server_default='completed', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['query_id'], ['qa_queries.id'], name=op.f('fk_search_events_query_id_qa_queries'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subtask_id'], ['qa_subtasks.id'], name=op.f('fk_search_events_subtask_id_qa_subtasks'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_search_events'))
    )
    op.create_index('ix_search_events_created_at', 'search_events', ['created_at'], unique=False)
    op.create_index('ix_search_events_provider_name', 'search_events', ['provider_name'], unique=False)
    op.create_index('ix_search_events_query_id', 'search_events', ['query_id'], unique=False)
    op.create_index('ix_search_events_search_scope', 'search_events', ['search_scope'], unique=False)
    op.create_index('ix_search_events_status', 'search_events', ['status'], unique=False)
    op.create_index('ix_search_events_subtask_id', 'search_events', ['subtask_id'], unique=False)
    op.create_table('tool_invocations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('query_id', sa.UUID(), nullable=False),
    sa.Column('subtask_id', sa.UUID(), nullable=True),
    sa.Column('tool_name', sa.String(length=100), nullable=False),
    sa.Column('tool_scope', sa.String(length=100), nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('pending', 'running', 'completed', 'failed', name='tool_invocation_status_enum'), server_default='pending', nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('result_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['query_id'], ['qa_queries.id'], name=op.f('fk_tool_invocations_query_id_qa_queries'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subtask_id'], ['qa_subtasks.id'], name=op.f('fk_tool_invocations_subtask_id_qa_subtasks'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tool_invocations'))
    )
    op.create_index('ix_tool_invocations_created_at', 'tool_invocations', ['created_at'], unique=False)
    op.create_index('ix_tool_invocations_query_id', 'tool_invocations', ['query_id'], unique=False)
    op.create_index('ix_tool_invocations_status', 'tool_invocations', ['status'], unique=False)
    op.create_index('ix_tool_invocations_subtask_id', 'tool_invocations', ['subtask_id'], unique=False)
    op.create_index('ix_tool_invocations_tool_name', 'tool_invocations', ['tool_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tool_invocations_tool_name', table_name='tool_invocations')
    op.drop_index('ix_tool_invocations_subtask_id', table_name='tool_invocations')
    op.drop_index('ix_tool_invocations_status', table_name='tool_invocations')
    op.drop_index('ix_tool_invocations_query_id', table_name='tool_invocations')
    op.drop_index('ix_tool_invocations_created_at', table_name='tool_invocations')
    op.drop_table('tool_invocations')
    op.drop_index('ix_search_events_subtask_id', table_name='search_events')
    op.drop_index('ix_search_events_status', table_name='search_events')
    op.drop_index('ix_search_events_search_scope', table_name='search_events')
    op.drop_index('ix_search_events_query_id', table_name='search_events')
    op.drop_index('ix_search_events_provider_name', table_name='search_events')
    op.drop_index('ix_search_events_created_at', table_name='search_events')
    op.drop_table('search_events')
    op.drop_index('ix_qa_evidence_subtask_id', table_name='qa_evidence')
    op.drop_index('ix_qa_evidence_source_kind', table_name='qa_evidence')
    op.drop_index('ix_qa_evidence_source_domain', table_name='qa_evidence')
    op.drop_index('ix_qa_evidence_query_id', table_name='qa_evidence')
    op.drop_index('ix_qa_evidence_node_id', table_name='qa_evidence')
    op.drop_index('ix_qa_evidence_document_version_id', table_name='qa_evidence')
    op.drop_index('ix_qa_evidence_document_id', table_name='qa_evidence')
    op.drop_index('ix_qa_evidence_created_at', table_name='qa_evidence')
    op.drop_table('qa_evidence')
    op.drop_index('ix_audit_events_subtask_id', table_name='audit_events')
    op.drop_index('ix_audit_events_session_id', table_name='audit_events')
    op.drop_index('ix_audit_events_query_id', table_name='audit_events')
    op.drop_index('ix_audit_events_event_type', table_name='audit_events')
    op.drop_index('ix_audit_events_created_at', table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index('ix_verification_reports_query_id', table_name='verification_reports')
    op.drop_index('ix_verification_reports_created_at', table_name='verification_reports')
    op.drop_table('verification_reports')
    op.drop_index('ix_security_events_severity', table_name='security_events')
    op.drop_index('ix_security_events_session_id', table_name='security_events')
    op.drop_index('ix_security_events_query_id', table_name='security_events')
    op.drop_index('ix_security_events_created_at', table_name='security_events')
    op.drop_table('security_events')
    op.drop_index('ix_qa_subtasks_status', table_name='qa_subtasks')
    op.drop_index('ix_qa_subtasks_query_id', table_name='qa_subtasks')
    op.drop_index('ix_qa_subtasks_parent_subtask_id', table_name='qa_subtasks')
    op.drop_index('ix_qa_subtasks_created_at', table_name='qa_subtasks')
    op.drop_table('qa_subtasks')
    op.drop_index('ix_qa_answers_status', table_name='qa_answers')
    op.drop_index('ix_qa_answers_created_at', table_name='qa_answers')
    op.drop_table('qa_answers')
    op.drop_index('ix_freshness_checks_query_id', table_name='freshness_checks')
    op.drop_index('ix_freshness_checks_document_version_id', table_name='freshness_checks')
    op.drop_index('ix_freshness_checks_document_id', table_name='freshness_checks')
    op.drop_index('ix_freshness_checks_created_at', table_name='freshness_checks')
    op.drop_index('ix_freshness_checks_check_status', table_name='freshness_checks')
    op.drop_table('freshness_checks')
    op.drop_index('ix_trusted_source_chunks_text_tsv', table_name='trusted_source_chunks', postgresql_using='gin')
    op.drop_index('ix_trusted_source_chunks_document_id', table_name='trusted_source_chunks')
    op.drop_index('ix_trusted_source_chunks_created_at', table_name='trusted_source_chunks')
    op.drop_table('trusted_source_chunks')
    op.drop_index('ix_qa_queries_status', table_name='qa_queries')
    op.drop_index('ix_qa_queries_session_id', table_name='qa_queries')
    op.drop_index('ix_qa_queries_message_id', table_name='qa_queries')
    op.drop_index('ix_qa_queries_finished_at', table_name='qa_queries')
    op.drop_index('ix_qa_queries_created_at', table_name='qa_queries')
    op.drop_table('qa_queries')
    op.drop_index('ix_trusted_source_documents_source_domain', table_name='trusted_source_documents')
    op.drop_index('ix_trusted_source_documents_created_at', table_name='trusted_source_documents')
    op.drop_index('ix_trusted_source_documents_content_hash', table_name='trusted_source_documents')
    op.drop_table('trusted_source_documents')
    op.drop_index('ix_qa_messages_session_id', table_name='qa_messages')
    op.drop_index('ix_qa_messages_created_at', table_name='qa_messages')
    op.drop_table('qa_messages')
    op.drop_index('ix_trusted_source_sync_runs_status', table_name='trusted_source_sync_runs')
    op.drop_index('ix_trusted_source_sync_runs_source_domain', table_name='trusted_source_sync_runs')
    op.drop_index('ix_trusted_source_sync_runs_created_at', table_name='trusted_source_sync_runs')
    op.drop_table('trusted_source_sync_runs')
    op.drop_index('ix_qa_sessions_status', table_name='qa_sessions')
    op.drop_index('ix_qa_sessions_expires_at', table_name='qa_sessions')
    op.drop_index('ix_qa_sessions_created_at', table_name='qa_sessions')
    op.drop_index('ix_qa_sessions_channel_external_user_id', table_name='qa_sessions')
    op.drop_index('ix_qa_sessions_channel_external_chat_id', table_name='qa_sessions')
    op.drop_table('qa_sessions')
    # ### end Alembic commands ###
