sources:
  seed_urls:
    - "https://meganorm.ru/mega_doc/norm/sp_svod-pravil/sp_svod-pravil_0.html"
    - "https://meganorm.ru/mega_doc/norm/snip_stroitelnye-normy-i-pravila/snip_stroitelnye-normy-i-pravila_0.html"
    - "https://meganorm.ru/list2/64522-0.htm"
    - "https://meganorm.ru/list2/64511-0.htm"
