statuses:
  active:
    - "действует"
    - "действующий"
    - "взамен"
  inactive:
    - "утратил силу"
    - "не действует"
    - "заменен"
    - "отменен"
    - "частично отменен"
    - "проект"
    - "приостановлено действие"
