/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js conventions and kept in source control
// so the placeholder app can build before the richer Stage 2 UI is added.
